// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Semester6.Migrations
{
    [DbContext(typeof(ToetsContext))]
    [Migration("20250402092559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Semester6.Models.Docent", b =>
                {
                    b.Property<int>("DocentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocentId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocentId");

                    b.ToTable("Docenten");
                });

            modelBuilder.Entity("Semester6.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("Semester6.Models.Toets", b =>
                {
                    b.Property<int>("ToetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToetsId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VakId")
                        .HasColumnType("int");

                    b.HasKey("ToetsId");

                    b.HasIndex("VakId");

                    b.ToTable("Toetsen");
                });

            modelBuilder.Entity("Semester6.Models.ToetsResultaat", b =>
                {
                    b.Property<int>("ToetsResultaatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToetsResultaatId"));

                    b.Property<decimal>("Cijfer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsHerkansing")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ToetsId")
                        .HasColumnType("int");

                    b.HasKey("ToetsResultaatId");

                    b.HasIndex("ToetsId");

                    b.HasIndex("StudentId", "ToetsId", "IsHerkansing")
                        .IsUnique();

                    b.ToTable("ToetsResultaten");
                });

            modelBuilder.Entity("Semester6.Models.Vak", b =>
                {
                    b.Property<int>("VakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VakId"));

                    b.Property<int>("DocentId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VakId");

                    b.HasIndex("DocentId");

                    b.ToTable("Vakken");
                });

            modelBuilder.Entity("Semester6.Models.Toets", b =>
                {
                    b.HasOne("Semester6.Models.Vak", "Vak")
                        .WithMany("Toetsen")
                        .HasForeignKey("VakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vak");
                });

            modelBuilder.Entity("Semester6.Models.ToetsResultaat", b =>
                {
                    b.HasOne("Semester6.Models.Student", "Student")
                        .WithMany("ToetsResultaten")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semester6.Models.Toets", "Toets")
                        .WithMany("ToetsResultaten")
                        .HasForeignKey("ToetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Toets");
                });

            modelBuilder.Entity("Semester6.Models.Vak", b =>
                {
                    b.HasOne("Semester6.Models.Docent", "Docent")
                        .WithMany("Vakken")
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docent");
                });

            modelBuilder.Entity("Semester6.Models.Docent", b =>
                {
                    b.Navigation("Vakken");
                });

            modelBuilder.Entity("Semester6.Models.Student", b =>
                {
                    b.Navigation("ToetsResultaten");
                });

            modelBuilder.Entity("Semester6.Models.Toets", b =>
                {
                    b.Navigation("ToetsResultaten");
                });

            modelBuilder.Entity("Semester6.Models.Vak", b =>
                {
                    b.Navigation("Toetsen");
                });
#pragma warning restore 612, 618
        }
    }
}
